### ISSUE TITLE
Unexpected ivAdd overflow behavior

### ISSUE THREAD

**Issue by centromere** [haskell-crypto/cryptonite#160]
When testing the [`ivAdd`](https://www.stackage.org/haddock/lts-8.13/cryptonite-0.21/Crypto-Cipher-Types.html#v:ivAdd) function I noticed that when intentionally given a value of all 0xFF bytes, it rolls over to `0x00...0x01`. My expectation was that it would roll over to `0x00...0x00`. Is this intended behavior?

> λ> import Data.Maybe
> λ> import Data.ByteArray
> λ> import Data.ByteString
> λ> import Crypto.Cipher.Types
> λ> import Crypto.Cipher.AES
> λ> let n = fromJust . makeIV $ ("\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255\255" :: ByteString) :: IV AES256
> λ> Data.ByteString.unpack (convert n :: ByteString)
> [255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255]
> λ> Data.ByteString.unpack $ (convert $ ivAdd n 1 :: ByteString)
> [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1]

**Comment by ocheron** [comment]
In the implementation the carry is added back to the least significant byte.

This could just be a bug because ivAdd is used by ctrCombine, in turn demonstrated in Crypto.Tutorial.

If I set the IV to 0xffffffffffffffffffffffffffffffff or very close, this does not interoperate
with `openssl enc -aes-256-ctr`. Whereas when the IV is random, one implementation
can decrypt what the other encrypted.

**Comment by vincenthz** [comment]
yeah that looks like a bug indeed.

**Comment by ocheron** [comment]
Fixed with #164.
