### ISSUE TITLE
Build with `Cabal 1.16`?

### ISSUE THREAD

**Issue by Gabriella439** [haskell-crypto/cryptonite#163]
Would it be possible to decrease the lower bound on `Cabal` to `1.16`?

The reason I'm asking is that `multi-ghc-travis` tests each version of `ghc` with the version of `Cabal` that ships with it, and `ghc-7.6.3` comes with `cabal-install-1.16`

**Comment by tekul** [comment]
This only seems to have [changed recently](https://github.com/haskell-crypto/cryptonite/commit/baa2b6d9c927e101629e10126356b03b2b644deb) in order to support  `extra-doc-files` which is apparently only supported from 1.18 onwards. I don't know much about supporting different cabal versions simultaneously but perhaps you have an idea there?

Alternatively, is it perhaps possible to get the travis build stuff to update cabal beforehand?

**Comment by Gabriella439** [comment]
If the lower bound is necessary in this case then that's fine.  I have some other ways that I can work around this.  I was just checking to see if the lower bound was required and it seems like it is

**Comment by tekul** [comment]
Ok, I'll close this then.

Incidentally, I just found out that github has very convenient "blame" support. Just hit `b` in the file view window and you can see [why/when a specific line was changed](https://github.com/haskell-crypto/cryptonite/blame/master/cryptonite.cabal#L38).

**Comment by vincenthz** [comment]
I can't seem to find the link where we discussed this (or maybe I just imagined the discussion), but I think we're on the way to drop 7.6 support anyway.
