### ISSUE TITLE
Convert Digest to ByteString?

### ISSUE THREAD

**Issue by Xandaros** [haskell-crypto/cryptonite#185]
Right now, it seems you can only use `Digest`'s `Show` instance to get any data out of it, which is really not ideal if you need to do anything other than displaying it.
Right now, I use `fst . head . readHex . show` to convert the `Digest` to an `Integer`, which happens to be what I need it as, but I feel like the option to get a `ByteString` would be the most sensible option.

In the end, that is what the string output by `show` represents - each character is a nibble.

**Comment by ocheron** [comment]
Please look at #146 and #129.

**Comment by Xandaros** [comment]
Okay, so there's a `convert` function. Might be a good idea to link to that in the documentation for people who are unfamiliar with the memory package.

**Comment by ocheron** [comment]
Yes you must be right, this question comes up rather often.

**Comment by ocheron** [comment]
Some documentation added in c6c715f465e345993fd456ce6e02f923a7530f0a.

**Comment by orionsread** [comment]
A similar issue: I want to convert from `Digest h` to `ShortByteString` -- this should be a no-op because they are both `ByteArray#` under the hood. Using the `ByteArrayAccess` api I end up doing an extraneous copy. If there was an internal module which exposed the `Digest` constructor this would not be an issue.
