### ISSUE TITLE
Build failure on GHC 7.8.4 with foundation-0.0.13

### ISSUE THREAD

**Issue by RyanGlScott** [haskell-crypto/cryptonite#207]
As observed in [this Travis build](https://travis-ci.org/scotty-web/wai-middleware-static/jobs/309686391#L784), `cryptonite-0.24` fails to build on GHC 7.8.4 against `foundation-0.0.13`:

```
[ 37 of 120] Compiling Crypto.Hash.Types ( Crypto/Hash/Types.hs, dist/build/Crypto/Hash/Types.o )

Crypto/Hash/Types.hs:66:22:
    No instance for (ByteArrayAccess (F.UArray Word8))
      arising from the 'deriving' clause of a data type declaration
    Possible fix:
      use a standalone 'deriving instance' declaration,
        so you can specify the instance context yourself
    When deriving the instance for (ByteArrayAccess (Digest a))
```

`foundation-0.0.13` appears to be involved, since `cryptonite-0.24` _does_ build correctly on GHC 7.8.4 against `foundation-0.0.15`.

**Comment by vincenthz** [comment]
I haven't foreseen this, but that make sense. memory-0.14.9 which I released yesterday now depends on basement's implementation, and you need at least foundation 0.0.14 to have basement. so that leave foundation-0.0.13 with it's own F.UArray type (which is not basement's), so no instances.

I'm not sure if there's anything that can be done to express this state of things (also whether it's worth it, 7.8 is getting long in the tooth).

somewhat related to #206

**Comment by RyanGlScott** [comment]
OK. Can you simply adjust the lower version bounds on `foundation` to require 0.0.14 or later?

**Comment by phadej** [comment]
Observable in https://github.com/haskell-servant/servant/pull/868 and travis job: https://travis-ci.org/haskell-servant/servant/jobs/310251850

**Comment by phadej** [comment]
The trickiness is that https://matrix.hackage.haskell.org/package/cryptonite supports even 7.6, when latest foundation only 7.8: https://matrix.hackage.haskell.org/package/foundation

Setting `foundation >= 0.14` would effectively drop GHC 7.6 support.

*EDIT:* though 7.6 isn't even tested in travis matrix, so seems to compile (hopefully also work!) by accident.

**Comment by hvr** [comment]
This is messy... what's the conclusion/summary? 

Is revising `cryptonite-0.23`'s and `cryptonite-0.24`'s meta-data to require `foundation >= 0.0.14` the smallest necessary action to make `cryptonite`'s version reflect its exposed/accessible API more accurately and make those invalid configurations inaccessible to the cabal solver (at the cost of amputating GHC 7.6 install-plans which as I understand weren't officially supported anyway)?

**Comment by phadej** [comment]
There is an interesting interaction between `cryptonite` and its dependencies: `memory`, `foundation` and `basement`.  The dependency graph isn't static, e.g. `memory-0.14.9` doesn't depend on ` foundation`, therefore having not intended combination of `foundation-0.0.13` and `memory-0.14.9` is possible.

Given what's possible with [revisions](https://github.com/haskell-infra/hackage-trustees/blob/master/revisions-information.md), we can also revise `cryptonite-0.24` and `cryptonite-0.23` with `< memory-0.14.9` bound. This bound will cut less valid invalid plans, as `memory-0.14.9` is a recent release (under a week at the moment).

I'll make the revisions adding `memory <0.14.9` on 2017-12-08. @vincenthz please comment if you would rather prefer the `foundation >= 0.0.14`.

*Note:* both revisions would invalidate some freezed configurations, we cannot work around that.

More details on the issue and considered options is on [Hackage Trustee issue tracker issue](https://github.com/haskell-infra/hackage-trustees/issues/119). I also made a [PR](https://github.com/haskell-crypto/cryptonite/pull/208) to for a more precise solution via automatic flag, to disallow only `foundation <0.14, memory >=0.14.9` combinations.

**Comment by vincenthz** [comment]
I don't find any of the solution here satifactory; I don't think there's way to express what need to be done here, so I reverted/tweaked memory to allow both instances to live in parallel in certain case. the current downside is that I have a unwanted dependency for now. so eventually that will be removed too once the rest of cryptonite is catching up (aka #206) and that there's no lts depending on this.

@RyanGlScott if you're still in position to test (I seen that you apply a workaround so might not be able to), could you try to see that memory 0.14.10 fix all the building problem you had.

Otherwise closing for now, it shouldn't really have further consequences for now (unless something I missed)

**Comment by RyanGlScott** [comment]
Thanks! My previously failing Travis builds are now working again with `memory-0.14.10`.

**Comment by vincenthz** [comment]
glad to hear @RyanGlScott
