### ISSUE TITLE
Add 'randomNumber' function

### ISSUE THREAD

**Issue by chshersh** [haskell-crypto/cryptonite#209]
I really would like to use `cryptonite` in my packages. But I find it too cumbersome to use. For example, it's not so easy to simply generate random number. I've discovered this function in `cardano-sl` for random number generation:

https://github.com/input-output-hk/cardano-sl/blob/400157238d234fd1cfcb0c29c596326287d7c698/crypto/Pos/Crypto/Random.hs#L48

I don't think it's a good idea to copy-paste it into every project which requires random number generation. Also, maybe it's a good idea to use `Natural` instead of `Integer`?

**Comment by vincenthz** [comment]
I haven't double checked but IIRC the modulo bias has been fixed from the number generation already; otherwise I'm fine adding this function directly in.

As to `Natural` instead of `Integer`, this would be indeed the right thing to do now, but most API are older than base's `Natural` (by years) and thus it's a bit of a upgrade nightmare to move from `Integer` to `Natural`

**Comment by chshersh** [comment]
I noticed that with `Natural` it's harder to implement the following function:

 ```haskell
randomNumberInRange :: MonadRandom m => Integer -> Integer -> m Integer
```

if you want to support ranges like `[-5, 10]`.

**Comment by vincenthz** [comment]
it's probably not too bad, you generate a natural in the right range (0,15) and add the referencial start (`-5`)

**Comment by chshersh** [comment]
But this involves couple conversions from `Integer` to `Natural` and back. I don't know how fast this conversion is, didn't perform such benchmarks. Maybe it's negligible.

**Comment by vincenthz** [comment]
I haven't actually checked, but I'ld expect the conversion to be cheap since it's the same underlaying GMP Limbs stuff

https://hackage.haskell.org/package/base-4.9.0.0/docs/src/GHC.Natural.html#Natural
https://hackage.haskell.org/package/integer-gmp-1.0.0.1/docs/GHC-Integer-GMP-Internals.html#t:BigNat

**Comment by ocheron** [comment]
Just to note the obvious: there is a function `generateBetween` in module `Crypto.Number.Generate`. Bias concerns are already addressed if the range is large enough.

**Comment by chshersh** [comment]
@ocheron Thanks! I checked the code. Looks like what I need. If the modulo bias is fixed in this function on version on Stackage then this issue can be closed.

* https://www.stackage.org/haddock/lts-10.5/cryptonite-0.24/Crypto-Number-Generate.html#v:generateMax

**Comment by ocheron** [comment]
Yes all of that hasn't changed since cryptonite-0.23.
