### ISSUE TITLE
-maes does not work on all Mac OS X

### ISSUE THREAD

**Issue by FranklinChen** [haskell-crypto/cryptonite#21]
On Mac OS X 10.7.5 (the last version runnable on my 2008 MacBook), cryptonite does not build because the C compiler on it does not know `-maes`.

I can still build cryptonite with `-f -support_aesni`, however. Maybe this should be mentioned in the README, or else a Mac OS X version check performed automatically.

**Comment by ghost** [comment]
Same here, stuck on OS X 10.7.5 because of old hardware. Cryptonite installation fails because cc1 error: unrecognized command line option "-maes".

**Comment by NicolasDP** [comment]
Hello @FranklinChen ,

I think this is because it is not supported by cryptonite: https://github.com/vincenthz/cryptonite#support

Maybe a work-around could be to add a **_FAQ**_ in the README to help to fix this issue (providing the answer warns that in this case cryptonite may not be as performant).

@osmartormenajr : does disabling the aesni support work for you?

**Comment by vincenthz** [comment]
@NicolasDP is right, it's sadly not supported by default, just because I can't rely on cabal to tell me osx's version or the compiler's version, but on the bright side, it's very easy to build on 10.7 by just disabling a flag. I added some information in the README.

@FranklinChen @osmartormenajr can you report whether those instructions fixes your problem ?

**Comment by FranklinChen** [comment]
@vincenthz Sure, the instructions seem clear enough.

**Comment by vincenthz** [comment]
Thanks. closing for the lack of any better solution for now
