### ISSUE TITLE
Show instance of Digest

### ISSUE THREAD

**Issue by vu3rdd** [haskell-crypto/cryptonite#244]
The `Digest a` has a `Show` instance that gives back a hex encoded value of the Digest value. This is nice and convenient. However, doesn't it break the `show . read == id` identity? Wouldn't it be better to instead have a separate function that does it instead of having a `Show` instance?

Sorry if I overlooked something. Happy to contribute a patch if this is a good idea. Thanks.

**Comment by ocheron** [comment]
IIRC the Read instance parses from the same format produced by the Show instance so I don't think it breaks the equation.

**Comment by vincenthz** [comment]
@vu3rdd with the benefits of insight, I wouldn't use Show for anything but debugging in Haskell, but as it stands this is what we have. I think @ocheron is correct that `show . read` is not broken.

Otherwise, this requires some globally available functions/class to "visit" the content of binary stuff; possibly something for the `basement` and/or `memory` packages
