### ISSUE TITLE
nacl box/secretbox/HSalsa20 compatibility

### ISSUE THREAD

**Issue by sirlensalot** [haskell-crypto/cryptonite#283]
I've been trying to assemble a compatibility layer with nacl's "box" (https://nacl.cr.yp.to/box.html) assuming that cryptonite would have the necessary primitives, but it seems I'm coming up short. 

The description of this procedure (https://cr.yp.to/highspeed/naclcrypto-20090310.pdf, introduction) describes creation of a DH key, which seems to be possible using `Crypto.PubKey.Curve25519`:

> * Section 2: Alice creates a 32-byte secret key _a_ and a 32-byte public key A. ...
> * Section 2, continued: Bob creates a 32-byte secret key _b_ and a 32-byte public key B. ...
> * Section 5: Alice, using Alice’s secret key _a_ and Bob’s public key B, computes a 32-byte secret _k_. Bob can compute the same secret using Bob’s secret key _b_ and Alice’s public key A.

It then describes the process of encrypting a "packet":

>The remaining three steps are specific to one packet:
> * Section 7: Alice, using a 24-byte nonce (unique packet number) _n_ that will never be reused for other packets to (or from) Bob, expands the shared secret _k_ into a long stream of secret bytes. Bob, given the nonce, can compute the same stream.
> * Section 9: Alice uses the long stream, except for the first 32 bytes, to encrypt the packet m.
> * Section  9,  continued:  Alice  uses  the  first  32  bytes  of  the  long  stream  to compute an authenticator of the encrypted packet.

It is the creation of the "long stream", which seems to require HSalsa20, that I can't seem to do with `cryptonite`. The authenticator is presumably possible using `Crypto.MAC.Poly1305` but I'm not sure how to do it (being a crypto noob).

If any primitives are indeed missing it would seem to be a good idea to include them as box/secretbox are widely used in javascript and other languages. Ideally the whole procedure would be available but I could also see this being in a separate `cryptonite-box` package or something.

**Comment by ocheron** [comment]
There should probably be a simpler API to do this but as #279 explained it's possible to get HSalsa20 result out of the XSalsa state like this:
```haskell
import qualified Data.ByteArray as BA
import qualified Data.ByteString as B

import           Crypto.Cipher.Salsa (State(..))
import qualified Crypto.Cipher.XSalsa as XSalsa

hSalsa20 :: (BA.ByteArrayAccess key, BA.ByteArrayAccess nonce)
         => key -> nonce -> B.ByteString
hSalsa20 k n =
    let suffix = B.replicate 8 0
        State ctx = XSalsa.initialize 20 k (B.append (BA.convert n) suffix)
     in BA.concat [ BA.view ctx 4 16, BA.view ctx 44 16 ]
```

EDIT: although this is likely to depend on CPU endianness, one more sign a clean API is desirable.

**Comment by yutotakano** [comment]
Sorry to revive an old issue, but I was attempting to build both a Crypto_SecretBox and Crypto_Box implementation using `cryptonite` primitives, just as your attempts above. How much of a guarantee can I assume about memory safety of e.g. shared keys that are [computed as part of the example implementation](https://github.com/haskell-crypto/cryptonite/blob/b96ec42d3ebbe0d05854332c231c60f908518a83/Crypto/Tutorial.hs#L189)?

In `libsodium`, they [use](https://github.com/jedisct1/libsodium/blob/0a6178f20373b34f36e91a03d7ca0d4c22462217/src/libsodium/crypto_box/crypto_box_easy.c#L34) memset on the computed shared key after everything, but since there's nothing like it in the cryptonite example, I want to ask if either: we are blindly trusting the garbage collector to come around after a while, or the example is flawed.
