### ISSUE TITLE
Exporting HashAlgorithmASN1's function for external use

### ISSUE THREAD

**Issue by moll** [haskell-crypto/cryptonite#318]
Hey again!

Thanks for maintaining Cryptonite, too! Would you consider exporting the instance function of [`HashAlgorithmASN1`](https://hackage.haskell.org/package/cryptonite-0.25/docs/Crypto-PubKey-RSA-PKCS15.html#t:HashAlgorithmASN1) (`hashDigestASN1`)? I've got a use-case where I need to sign a hash in PKCS 1.5, but don't have access to the pre-hashed data to feed `Crypto.PubKey.RSA.PKCS15.sign` since it insists in hashing before prepending the ASN.1 structure to indicate the hash function.

Thanks in advance!

**Comment by moll** [comment]
In a related comment, the `Crypto.PubKey.RSA.PKCS15.sign` signature is a little inconvenient to use when one doesn't want hashing as the `hashAlg` parameter is ambiguous if you give it a `Nothing`. Perhaps those two cases should be split into two functions, one for always hashing, the other for never.

**Comment by ocheron** [comment]
In the ECDSA module we have functions signDigest and verifyDigest that take a `Digest hash` instead of the message. Would that be enough for your use case?

**Comment by moll** [comment]
Yeah, that'd do it, too. Thanks!

**Comment by moll** [comment]
In light of the `*Digest` functions you allude to, and https://github.com/haskell-crypto/cryptonite/issues/318#issuecomment-604407734, perhaps the plain `sign` and `verify` could drop the hash argument to simplify type inference?

**Comment by ocheron** [comment]
Yes you're right about the Nothing case.
But I think it's best not to change existing API, create new functions instead.

**Comment by wwwater** [comment]
We have the same use-case, when the original message isn't available, and we need to verify the digest signature. What I ended up doing is passing `Nothing` to the `verify` function, but then I still need to prefix the hash with what's in `hashDigestASN1`, and so I had to copy the prefixes from the source code. 

As already mentioned in the thread, I guess it would make more sense to have an additional `verifyDigest` function, instead of exposing `hashDigestASN1`, since the thing about prefixes is quite confusing for non-experts in cryptography.
