### ISSUE TITLE
API: Can't use makeIV with GCM

### ISSUE THREAD

**Issue by centromere** [haskell-crypto/cryptonite#47]
In GCM, IVs are 12-bytes long, and if they're longer than that GHASH is run on them. This is implemented properly [here](https://github.com/vincenthz/cryptonite/blob/6a5307189faa8ee6ed626057ab855a447edfd666/cbits/cryptonite_aes.c#L354), however, `len` will never be 12 when using `makeIV` or `nullIV`. Because of [this](https://github.com/haskell-crypto/cryptonite/blob/2139bb1f1d9dd46cc07c300ecad256f85d771feb/Crypto/Cipher/Types/Block.hs#L154), `len` will always be 16. While I can pass a raw 96-bit ByteString to `aeadInit`, I'd like to use `ivAdd`.

**Comment by vincenthz** [comment]
you're the second one to report this #6 , so it's very likely we have a documentation problem at best, or that something should be done to make it clearer or more type friendly.

Because GCM IVs are not restricted in length (it could technically be any size above or equal to 12 bytes), any `ByteArrayAccess`-constrainted type can be used, and the BlockCipher sized IV type shouldn't be used.
