### ISSUE TITLE
Adding support for SHAKE128, SHAKE256

### ISSUE THREAD

**Issue by tittoassini** [haskell-crypto/cryptonite#76]
Can this be derived directly from the existing Keccak implementation?

**Comment by vincenthz** [comment]
I think it's simple to derive from the implementation, but don't really have the need for it personally. Maybe a good idea for a PR ? :)

**Comment by ocheron** [comment]
Since this is a functional language and SHAKE is about arbitrary-length output I tried to explore how to overcome fixed-sized `Digest a` types:

1. [sha3-shake-typelits](https://github.com/haskell-crypto/cryptonite/compare/master...ocheron:sha3-shake-typelits) uses type-level literals to add SHAKE support as `HashAlgorithm` instances

2. [sha3-shake-xof](https://github.com/haskell-crypto/cryptonite/compare/master...ocheron:sha3-shake-xof) creates a clone of `Crypto.Hash` API, but with a generalization providing an output stream instead of `Digest` values

I realize the 2nd approach is a lot of code just for SHAKE.
The "typelits" version seem to work correctly with GHC 7.8.4, 7.10.3 and 8.0.1.

It is also possible not to do any of this and choose a fixed-size output, for example 1 full round of squeezing. Then let the user truncate the result as desired (but not extend).

**Comment by ocheron** [comment]
SHAKE is available in cryptonite-0.22.
